export const fileType = {
  audio: "audio",
  xls: "xls",
  word: "word",
  pdf: "pdf",
  ppt: "ppt",
  archive: "archive",
  image: "image",
  video: "video",
  programming: "programming",
  font: "font",
  document: "document",
};

export default {
  "audio/aac": fileType.audio,
  "application/x-abiword": fileType.document,
  "application/x-freearc": fileType.archive,
  "image/avif": fileType.image,
  "video/x-msvideo": fileType.video,
  "application/vnd.amazon.ebook": fileType.document,
  "application/octet-stream": fileType.programming,
  "image/bmp": fileType.image,
  "application/x-bzip": fileType.archive,
  "application/x-bzip2": fileType.archive,
  "application/x-cdf": fileType.audio,
  "application/x-csh": fileType.programming,
  "text/css": fileType.programming,
  "text/csv": fileType.xls,
  "application/msword": fileType.word,
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    fileType.word,
  "application/vnd.ms-fontobject": fileType.font,
  "application/epub+zip": fileType.archive,
  "application/gzip": fileType.archive,
  "image/gif": fileType.image,
  "text/html": fileType.programming,
  "image/vnd.microsoft.icon": fileType.image,
  "text/calendar": fileType.txt,
  "application/java-archive": fileType.archive,
  "image/jpeg": fileType.image,
  "text/javascript": fileType.programming,
  "application/json": fileType.programming,
  "application/ld+json": fileType.programming,
  "audio/midi": fileType.audio,
  "audio/x-midi": fileType.audio,
  "audio/mpeg": fileType.audio,
  "video/mp4": fileType.video,
  "video/mpeg": fileType.video,
  "application/vnd.apple.installer+xml": fileType.programming,
  "application/vnd.oasis.opendocument.presentation": fileType.ppt,
  "application/vnd.oasis.opendocument.spreadsheet": fileType.xls,
  "application/vnd.oasis.opendocument.text": fileType.txt,
  "audio/ogg": fileType.audio,
  "video/ogg": fileType.video,
  "application/ogg": fileType.programming,
  "audio/opus": fileType.audio,
  "font/otf": fileType.font,
  "image/png": fileType.image,
  "application/pdf": fileType.pdf,
  "application/x-httpd-php": fileType.programming,
  "application/vnd.ms-powerpoint": fileType.ppt,
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    fileType.ppt,
  "application/vnd.rar": fileType.archive,
  "application/rtf": fileType.txt,
  "application/x-sh": fileType.programming,
  "image/svg+xml": fileType.image,
  "application/x-shockwave-flash": fileType.video,
  "application/x-tar": fileType.archive,
  "image/tiff": fileType.image,
  "video/mp2t": fileType.video,
  "font/ttf": fileType.font,
  "text/plain": fileType.txt,
  "application/vnd.visio": fileType.programming,
  "audio/wav": fileType.audio,
  "audio/webm": fileType.audio,
  "video/webm": fileType.video,
  "image/webp": fileType.image,
  "font/woff": fileType.font,
  "font/woff2": fileType.font,
  "application/xhtml+xml": fileType.programming,
  "application/vnd.ms-excel": fileType.xls,
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
    fileType.xls,
  "application/xml": fileType.document,
  "text/xml": fileType.document,
  "application/atom+xml": fileType.document,
  "application/xml": fileType.document,
  "application/vnd.mozilla.xul+xml": fileType.programming,
  "application/zip": fileType.archive,
  "video/3gpp": fileType.video,
  "audio/3gpp": fileType.audio,
  "video/3gpp2": fileType.video,
  "audio/3gpp2": fileType.audio,
  "application/x-7z-compressed": fileType.archive,
};
