const projectParams = [
  { comment: '% PROJECT MAIN INFORMATION' },
  { key: 'projectId', comment: '% Project ID' },
  { key: 'name', comment: '% Project official name' },
  { key: 'PrjPurpose', comment: '% Purpose of the project' },
  { key: 'PrjCOD', comment: '% Commercial Operation Date' },
  { key: 'HPPName', comment: '% Hydropower name' },
  { key: 'PrjAddress', comment: '% Project address' },
  { key: 'PrjNearTown', comment: '% Project nearest significant town or city' },
  { key: 'PrjDisFromNearTown', comment: '% Road distance from nearest town or city to project' },
  { key: 'PrjDirFromNearTown', comment: '% Direction to project from nearest town or city' },
  { key: 'PrjMainRoute', comment: '% Route to travel to project site from nearest town or city' },
  { comment: '' },
  { comment: '% Project owner' },
  { key: 'PrjOwner', comment: '% Project owner company name' },
  { key: 'PrjOwnerAddress', comment: ' % Project owner company address' },
  { key: 'PrjOwnerPhone', comment: '% Project owner company phone' },
  { key: 'PrjOwnerFax', comment: '% Project owner company fax' },
  { key: 'PrjOwnerEmail', comment: '% Project owner company email' },
  { key: 'PrjOwnerLicense', comment: '% Project owner company license number' },
  { key: 'PrjOwnerBankAccount', comment: '% Project owner company bank account' },
  { comment: '' },
  { comment: '%Project owner company representative' },
  { key: 'PrjOwnerRepresent', comment: '% Project owner company representative name' },
  { key: 'PrjOwnerRepresentPos', comment: '% Project owner company representative position' },
  { key: 'PrjOwnerRepresentPhone', comment: '% Project owner company representative phone' },
  { key: 'PrjOwnerRepresentEmail', comment: '% Project owner company representative email' },
  { key: 'PrjOwnerRepresentID', comment: '% Project owner company representative ID number' },
  { key: 'PrjOwnerContactPerson', comment: '% Project owner company contact person name' },
  { key: 'PrjOwnerContactPersonPhone', comment: '% Project owner company contact person phone' },
  { key: 'PrjOwnerContactPersonEmail', comment: '% Project owner company contact person Email' },
  { comment: '' },
];

const basinParams = [
  { comment: '% -----------------------------------------------------------------' },
  { comment: '% CATCHMENT INFORMATION' },
  { key: 'PrjRiverName', comment: '% Project river name' },
  { key: 'CatchArea', comment: '% Catchment area' },
  { key: 'RiverLength', comment: '% Main river length to dam location' },
  { key: 'MeanYearlyRainfall', comment: '% Lượng mưa trung bình nhiều năm X0' },
  { key: 'MeanYearlyEvaporation', comment: '% Tổn thất bốc hơi trung bình nhiều năm' },
  { key: 'FlowModulus', comment: '% Mô đun dòng chảy M0' },
  { key: 'MeanYearlyFlowRate', comment: '% Lưu lượng trung bình năm Q0' },
  { key: 'TotalInflow', comment: '% Tổng lượng dòng chảy W0' },
  { comment: '' },
  { key: 'PrjTopomapScale', comment: '% Topo-geologic study' },
  { key: 'ReservoirTopomapScale' },
  { key: 'IsRainfallRecordsAvailable', comment: '% Hydrologic analysis' },
  { key: 'IsInflowRecordsAvailable' },
  { key: 'WaterResourcePotential' },
  { comment: '' },
  { key: 'NumHPPsInCascade', comment: '%Hydropower plants cascade' },
  { key: 'TotalCapacityInCascade' },
  { comment: '' },
  { comment: '% ------------------------------------------------------------------' },
  { key: 'TotalNumRainStation', comment: '%Observation equipment' },
  { key: 'TotalNumSYNOPRainStation' },
  { key: 'TotalNumAWSRainStation' },
  { key: 'TotalNumProposedAWSRainStation' },
  { comment: '' },
];

const reservoirParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% RESERVOIR INFORMATION' },
  { key: 'reservoirName', label: 'ReservoirName', comment: '% Tên hồ chứa' },
  { key: 'reservoirDatumLevel', label: 'ReservoirDatumElev', comment: '% Cao trình đáy hồ' },
  { key: 'lowestPossibleDrawdownLevel', label: 'MinDrawdownWL', comment: '% Cao trình tháo cạn hồ' },
  { key: 'cavitationCriticalWaterLevel', label: 'CavitationWL', comment: '% Mực nước gây xâm thực' },
  { key: 'deadWaterLevel', label: 'DWL', comment: '% Mực chết' },
  { key: 'minimumWaterLevelToRunInstalledCapacity', label: 'MinWLwithPmax', comment: '% Mực nước tối thiểu phát Plm' },
  { key: 'floodPreventionWaterLevel', label: 'FloodPreventWL', comment: '% Mực nước phòng lũ' },
  { key: 'highestWaterLevelBeforeFlood', label: 'BeforeFloodWL', comment: '% Mực nước trước lũ' },
  { key: 'normalWaterLevel', label: 'NWL', comment: '% Mực nước dâng bình thường' },
  { key: 'designedFloodWaterLevel', label: 'DFWL', comment: '% Mực nước lũ thiết kế' },
  { key: 'maximumPermissibleFloodWaterLevel', label: 'MaxPermissibleWL', comment: '% Mực nước lũ kiểm tra' },
  { key: 'maximumPossibleWaterLevel', label: 'MaxPossibleWL', comment: '% Mực nước tràn đỉnh đập' },
  { key: 'upstreamHighestPossibleWaterLevel', label: 'UpstreamMaxWL', comment: '% Mực nước thượng lưu lớn nhất có thể' },
  { key: 'upstreamLowestPossibleWaterLevel', label: 'UpstreamMinWL', comment: '% Mực nước thượng lưu nhỏ nhất có thể' },
  { key: 'downstreamHighestPossibleWaterLevel', label: 'DownstreamMaxWL', comment: '% Mực nước hạ lưu lớn nhất có thể' },
  { key: 'downstreamLowestPossibleWaterLevel', label: 'DownstreamMinWL', comment: '% Mực nước hạ lưu nhỏ nhất có thể' },
  { comment: '% Thang quy mô lưu lượng về hồ' },
  { key: 'level1', label: 'LevelOneFlowRate', comment: '% Cấp 1' },
  { key: 'level2', label: 'LevelTwoFlowRate', comment: '% Cấp 2' },
  { key: 'level3', label: 'LevelThreeFlowRate', comment: '% Cấp 3' },
  { key: 'level4', label: 'LevelFourFlowRate', comment: '% Cấp 4' },
  { key: 'level5', label: 'LevelFiveFlowRate', comment: '% Cấp 5' },
  { key: 'designedFlood', label: 'QDesignedFlood', comment: '% Cấp 6 (Lũ thiết kế)' },
  { key: 'maximumFlood', label: 'QMaxFlood', comment: '% Cấp 7 (Lũ kiểm tra)' },
  { comment: '% Dung tích hồ' },
  { key: 'totalCapacity', label: 'ReservoirTotalCapacity', comment: '% Dung tích tổng' },
  { key: 'effectiveCapacity', label: 'ReservoirEffectiveCapacity', comment: '% Dung tích hữu ích' },
  { key: 'deadCapacity', label: 'ReservoirDeadCapacity', comment: '% Dung tích chết' },
  { comment: '' },
];

const damParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% DAM INFORMATION' },
  { key: 'longitude', label: 'DamLongitude', comment: '% Kinh độ' },
  { key: 'latitude', label: 'DamLatitude', comment: '% Vĩ độ' },
  { key: 'name', label: 'DamName', comment: '% Tên đập' },
  { key: 'elevation', label: 'DamTopELev', comment: '% Cao trình đỉnh đập' },
  { key: 'topWidth', label: 'DamTopWidth', comment: '% Bề rộng đỉnh đập' },
  { key: 'bottomWith', label: 'DamBottomWidth', comment: '% Bề rộng chân đập' },
  { key: 'topLength', label: 'DamTopLength', comment: '% Chiều dài mặt đập' },
  { key: 'height', label: 'DamMaxHeight', comment: '% Chiều cao lớn nhất' },
  { key: 'dischargeType', label: 'DamDischargeType', comment: '% Phân loại theo kiểu xả' },
  { key: 'damType', label: 'DamType', comment: '% Phân loại theo kết cấu' },
  { key: 'diversionCoefficient', label: 'DiversionCoeff', comment: '% Hệ số chuyển dòng' },
  { key: 'gatesPosition', label: 'GatesPosition', comment: '% Bố trí cửa xả lũ' },
  { key: 'powerHousePosition', label: 'PowerhousePosition', comment: '% Bố trí nhà máy' },
  { comment: '' },
];

const intakeParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% INTAKE INFORMATION' },
  { key: 'gateLocation', label: 'IntakeGateLocation', comment: '% Vị trí cửa nhận nước' },
  { key: 'crestElevation', label: 'IntakeCrestElev', comment: '% Cao trình ngưỡng' },
  { key: 'entranceWidth', label: 'IntakeEntranceWidth', comment: '% Độ rộng ngưỡng vào' },
  { key: 'entranceHeight', label: 'IntakeEntranceHeight', comment: '% Chiều cao ngưỡng vào' },
  { key: 'gates', label: 'NumOfIntakeGate', comment: '% Só lượng cửa' },
  { key: 'tunnelDiameter', label: 'IntakeDiameter', comment: '% Đường kính hầm' },
  { key: 'tunnelCenterElevation', label: 'IntakeCanalCenterElev', comment: '% Cao trình tâm hầm dẫn nước' },
  { key: 'coverDepth', label: 'RequiredCoverDepth', comment: '% Chiều sâu lớp nước tại cửa' },
  { comment: '' },
];

const surfaceParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% FLOOD GATES INFORMATION' },
  { key: 'gateType', label: 'SurfaceFloodGateType', comment: '% Kiểu cửa xả mặt' },
  { key: 'gateLiftType', label: 'SurfaceFloodGateLiftType', comment: '% Kiểu thiết bị nâng cửa xả mặt' },
  { key: 'gateLiftingDirection', label: 'SurfaceFloodGateLiftDirection', comment: '% Phương nâng cửa xả mặt' },
  { key: 'gateMotorType', label: 'SurfaceFloodGateMotorType', comment: '% Kiểu máy nâng cửa xả mặt' },
  { key: 'gateMotorSupply', label: 'SurfaceFloodGateMotorEnergySources', comment: '% Nguồn điện cho máy nâng' },
  { key: 'gateCrestElevation', label: 'SurfaceFloodGateCrestElev', comment: '% Cao trình ngưỡng cửa xả mặt' },
  { key: 'gateWidth', label: 'SurfaceFloodGateWidth', comment: '% Độ rộng cửa xả mặt' },
  { key: 'gateHeight', label: 'SurfaceFloodGateHeight', comment: '% Chiều cao cửa xả mặt' },
  { key: 'gateMaxOpen', label: 'SurfaceFloodGateMaxOpen', comment: '% Độ mở cực đại cửa xả mặt' },
  { key: 'gateNum', label: 'NumSurfaceFloodGate', comment: '% Số lượng cửa xả' },
  { comment: '' },
];

const conduitParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% CONDUIT GATES INFORMATION' },
  { key: 'gateType', label: 'ConduitFloodGateType', comment: '% Kiểu cửa xả sâu' },
  { key: 'gateLiftType', label: 'ConduitFloodGateLiftType', comment: '% Kiểu thiết bị nâng cửa xả sâu' },
  { key: 'gateLiftingDirection', label: 'ConduitFloodGateLiftDirection', comment: '% Phương nâng cửa xả sâu' },
  { key: 'gateMotorType', label: 'ConduitFloodGateMotorType', comment: '% Kiểu máy nâng cửa xả sâu' },
  { key: 'gateMotorSupply', label: 'ConduitFloodGateMotorEnergySources', comment: '% Nguồn điện cho máy nâng' },
  { key: 'gateCrestElevation', label: 'ConduitFloodGateCrestElev', comment: '% Cao trình ngưỡng cửa xả sâu' },
  { key: 'gateWidth', label: 'ConduitFloodGateWidth', comment: '% Độ rộng cửa xả sâu' },
  { key: 'gateHeight', label: 'ConduitFloodGateHeight', comment: '% Chiều cao cửa xả sâu' },
  { key: 'gateMaxOpen', label: 'ConduitFloodGateMaxOpen', comment: '% Độ mở cực đại cửa xả sâu' },
  { key: 'gateNum', label: 'NumConduitFloodGate', comment: '% Số lượng cửa xả' },
  { comment: '' },
];

const freefallParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% FREEFALL SPILLWAY INFORMATION' },
  { key: 'crestElevation', label: 'FreefallGateCrestElev', comment: '% Cao trình ngưỡng mặt' },
  { key: 'heightFromDatum', label: 'FreefallSectionHeight', comment: '% Chiều cao thân đập mặt cắt tràn' },
  { key: 'width', label: 'FreefallGateWidth', comment: '% Bề rộng thông thuỷ khoang tràn' },
  { key: 'height', label: 'FreefallGateHeight', comment: '% Chiều cao thông thuỷ khoang tràn' },
  { key: 'compartment', label: 'NumFreefallGate', comment: 'Số lượng khoang tràn' },
  { comment: '' },
];

const waterwayParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% WATERWAY INFORMATION' },
  { key: 'WaterwayType', comment: '% Kiểu đường dẫn nước' },
  { key: 'WaterwayConductType', comment: '% Kiểu dẫn nước' },
  { key: 'WaterwayConductMethod', comment: '% Phương pháp dẫn nước' },
  { key: 'NumWaterwayCanal', comment: '% Số lượng đường dẫn nước' },
  { key: 'WaterwayCanalSectionType', comment: '% Kiểu mặt cắt đường dẫn nước' },
  { key: 'WaterwayCanalSectionSize', comment: '% Kích thước mặt cắt đường dẫn nước' },
  { key: 'WaterwayCanalTotalLength', comment: '% Tổng chiều dài đường dẫn nước theo trục' },
  { comment: '' },
];

const surgeTankParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% SURGE TANK INFORMATION' },
  { key: 'SurgeTankType', comment: '% Kiểu tháp điều áp' },
  { key: 'SurgeTankSize', comment: '% Kích thước tháp điều áp' },
  { comment: '' },
];

const settlingTankParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% SETTLING TANK INFORMATION' },
  { key: 'SettlingTankLength', comment: '% Chiều dài bể lắng' },
  { key: 'SettlingTankWidth', comment: '% Chiều rộng bể lắng' },
  { key: 'SettlingTankDepth', comment: '% Chiều sâu bể lắng' },
  { comment: '' },
];

const headTankParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% HEAD TANK INFORMATION' },
  { key: 'HeadTankLength', comment: '% Chiều dài bể áp lực' },
  { key: 'HeadTankWidth', comment: '% Chiều rộng bể áp lực' },
  { key: 'HeadTankDepth', comment: '% Chiều sâu bể áp lực' },
  { comment: '' },
];

const penstockParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% PENSTOCK INFORMATION' },
  { key: 'PenstockTotalLength', comment: '% Tổng chiều dài đường ống áp lực' },
  { key: 'PenstockDiameter', comment: '% Đường kính trong đường ống áp lực' },
  { key: 'PenstockThickness', comment: '% Chiều dày thành ống áp lực' },
  { key: 'NumberOfPenstockLines', comment: '% Số lượng tuyến ống' },
  { comment: '' },
];

const powerhouseParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% POWERHOUSE INFORMATION' },
  { key: 'PowerhouseLat', comment: '% Vĩ độ nhà máy' },
  { key: 'PowerhouseLong', comment: '% Kinh độ nhà máy' },
  { key: 'PowerhouseLocation', comment: '% Vị trí nhà máy' },
  { key: 'PowerhouseType', comment: '% Kiểu nhà máy' },
  { key: 'NumUnits', comment: '% Số tổ máy' },
  { key: 'InstalledCapacity', comment: '% Công suất lắp máy' },
  { key: 'DesignedHead', comment: '% Cột nước thế kế' },
  { key: 'Qmax', comment: '% Lưu lượng phát cực đại' },
  { key: 'TurbineType', comment: '% Kiểu Turbine' },
  { key: 'TurbineActionType', comment: '% Nguyên lý hoạt động turbine' },
  { key: 'ShaftType', comment: '% Kiểu trục' },
  { key: 'TurbineInstalledElevation', comment: '% Cao trình turbine' },
  { key: 'TurbineRatedOutput', comment: '% Chiều sâu Hs' },
  { comment: '' },
];

const tailraceParams = [
  { comment: '% -------------------------------------------------------------------' },
  { comment: '% TAILRACE INFORMATION' },
  { key: 'MinTWL', comment: '% Vĩ độ nhà máy' },
  { key: 'MinOpeTWL', comment: '% Kinh độ nhà máy' },
  { key: 'MaxOpeTWL', comment: '% Vị trí nhà máy' },
  { key: 'DesignedFloodTWL', comment: '% Kiểu nhà máy' },
  { key: 'MaxFloodTWL', comment: '% Số tổ máy' },
  { key: 'MaxTWL', comment: '% Công suất lắp máy' },
  { key: 'TailraceLength', comment: '% Lưu lượng phát cực đại' },
  { key: 'TailraceWidth', comment: '% Kiểu Turbine' },
  { key: 'TailraceGradient', comment: '% Nguyên lý hoạt động turbine' },
  { key: 'TailraceSlopeCoefficient', comment: '% Kiểu trục' },
];

const technicalParams = {
  project: [{ key: 'PrjAreaDescription', comment: '% Project area economic and social condition' }, { comment: '' }],
  basin: [
    { comment: '%Comment on river basin' },
    { key: 'PrjRiverDescription', comment: '% River description' },
    { key: 'TopoGeologicDescription', comment: '% Comment on topo-geological condition' },
    { key: 'RainfallDescription', comment: '% Comment on hydrologic conditions' },
    { key: 'RunoffDescription', comment: '% Comment on runoff condition description' },
    { key: 'FDCDescription' },
    { key: 'CascadeMapDescription' },
    { key: 'RiverProfileDescription' },
    { key: 'RainfallObservationNetworkDescription' },
    { comment: '' },
  ],
  reservoir: [{ key: 'ReservoirDescription', comment: '% Comment on reservoir' }, { comment: '' }],
  dam: [{ key: 'technicalDescription', label: 'DamDescription', comment: '% Comment on dam structure' }, { comment: '' }],
  intake: [{ key: 'technicalDescription', label: 'IntakeDescription' }, { comment: '' }],
  surface: [
    { key: 'technicalDescription', label: 'SurfaceGatesDescription', comment: '%Comment on surface gates structure' },
    { comment: '' },
  ],
  conduit: [
    { key: 'technicalDescription', label: 'ConduitGatesDescription', comment: '%Comment on conduit gates structure' },
    { comment: '' },
  ],
  freefall: [
    { key: 'technicalDescription', label: 'FreefallDescription', comment: '%Comment on freefall structure' },
    { comment: '' },
  ],
  waterway: [{ key: 'WaterwayDescription' }, { comment: '' }],
  surgeTank: [{ key: 'SurgeTankDescription' }, { comment: '' }],
  settlingTank: [{ key: 'SettlingTankDescription' }, { comment: '' }],
  headTank: [{ key: 'HeadTankDescription' }, { comment: '' }],
  penstock: [{ key: 'PenstockDescription' }, { comment: '' }],
  powerhouse: [{ key: 'PowerhouseDescription' }, { comment: '' }],
  tailrace: [{ key: 'TailraceDescription' }, { comment: '' }],
};

const tableConfig = {
  rainObservation: {
    columns: [
      { label: `\\textbf{STT} & `, type: 'index' },
      { label: `\\textbf{Tên trạm} & `, field: 'stationName' },
      { label: `\\textbf{Kiểu trạm} & `, field: 'type' },
      { label: `\\textbf{Vĩ tuyến} & `, type: 'latitude' },
      { label: `\\textbf{Kinh tuyến} & `, field: 'longitude' },
      { label: `\\textbf{Số liệu} & `, field: 'data' },
      { label: `\\textbf{Thời khoảng} \\\\`, field: 'period' },
    ],
  },
  capacityCurve: {
    columns: [{ type: 'index' }, { field: 'z' }, { field: 'f' }, { field: 'v' }],
    headers: [
      { label: 'STT & ' },
      { label: 'Mực nước & ' },
      { label: 'Diện tích mặt hồ & ' },
      { label: 'Dung tích hồ \\\\ \n' },
      { label: ' & ' },
      { label: 'Z(m) & ' },
      { label: 'F($km^{2}$) & ' },
      { label: 'V($10^{6}m^{3}$) \\\\' },
    ],
  },
};

module.exports = {
  projectParams,
  basinParams,
  reservoirParams,
  damParams,
  intakeParams,
  surfaceParams,
  conduitParams,
  freefallParams,
  waterwayParams,
  surgeTankParams,
  settlingTankParams,
  headTankParams,
  penstockParams,
  powerhouseParams,
  tailraceParams,
  technicalParams,
  tableConfig,
};
